"""empty message

Revision ID: 523c23afa635
Revises: cad831b463bd
Create Date: 2023-06-03 17:27:35.979701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "523c23afa635"
down_revision = "cad831b463bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipe", sa.Column("ingredients", sa.String(length=1000), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipe", "ingredients")
    # ### end Alembic commands ###
